package com.rodrigo.javier.eox.hackermen.routerpointer.utilities

import com.rodrigo.javier.eox.hackermen.routerpointer.model.entities.ProvinciaEntity

class ListaProvincias {

    companion object {
        val provinciasList = arrayListOf<ProvinciaEntity>(
            ProvinciaEntity(1, "Arica", 1),
            ProvinciaEntity(2, "Parinacota", 1),
            ProvinciaEntity(3, "Iquique", 2),
            ProvinciaEntity(4, "El Tamarugal", 2),
            ProvinciaEntity(5, "Antofagasta", 3),
            ProvinciaEntity(6, "El Loa", 3),
            ProvinciaEntity(7, "Tocopilla", 3),
            ProvinciaEntity(8, "Chañaral", 4),
            ProvinciaEntity(9, "Copiapó", 4),
            ProvinciaEntity(10, "Huasco", 4),
            ProvinciaEntity(11, "Choapa", 5),
            ProvinciaEntity(12, "Elqui", 5),
            ProvinciaEntity(13, "Limarí", 5),
            ProvinciaEntity(14, "Isla de Pascua", 6),
            ProvinciaEntity(15, "Los Andes", 6),
            ProvinciaEntity(16, "Petorca", 6),
            ProvinciaEntity(17, "Quillota", 6),
            ProvinciaEntity(18, "San Antonio", 6),
            ProvinciaEntity(19, "San Felipe de Aconcagua", 6),
            ProvinciaEntity(20, "Valparaiso", 6),
            ProvinciaEntity(21, "Chacabuco", 7),
            ProvinciaEntity(22, "Cordillera", 7),
            ProvinciaEntity(23, "Maipo", 7),
            ProvinciaEntity(24, "Melipilla", 7),
            ProvinciaEntity(25, "Santiago", 7),
            ProvinciaEntity(26, "Talagante", 7),
            ProvinciaEntity(27, "Cachapoal", 8),
            ProvinciaEntity(28, "Cardenal Caro", 8),
            ProvinciaEntity(29, "Colchagua", 8),
            ProvinciaEntity(30, "Cauquenes", 9),
            ProvinciaEntity(31, "Curicó", 9),
            ProvinciaEntity(32, "Linares", 9),
            ProvinciaEntity(33, "Talca", 9),
            ProvinciaEntity(34, "Arauco", 10),
            ProvinciaEntity(35, "Bio Bío", 10),
            ProvinciaEntity(36, "Concepción", 10),
            ProvinciaEntity(37, "Ñuble", 10),
            ProvinciaEntity(38, "Cautín", 11),
            ProvinciaEntity(39, "Malleco", 11),
            ProvinciaEntity(40, "Valdivia", 12),
            ProvinciaEntity(41, "Ranco", 12),
            ProvinciaEntity(42, "Chiloé", 13),
            ProvinciaEntity(43, "Llanquihue", 13),
            ProvinciaEntity(44, "Osorno", 13),
            ProvinciaEntity(45, "Palena", 13),
            ProvinciaEntity(46, "Aisén", 14),
            ProvinciaEntity(47, "Capitán Prat", 14),
            ProvinciaEntity(48, "Coihaique", 14),
            ProvinciaEntity(49, "General Carrera", 14),
            ProvinciaEntity(50, "Antártica Chilena", 15),
            ProvinciaEntity(51, "Magallanes", 15),
            ProvinciaEntity(52, "Tierra del Fuego", 15),
            ProvinciaEntity(53, "Última Esperanza", 15),
            ProvinciaEntity(54, "Marga Marga", 6),
        )
    }
}

